spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pc_builder
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl.auto: validate
        jdbc:
          batch_size: 50